### ISSUE TITLE
Job failing at ReadStringIntoBuffer

### ISSUE THREAD

**Issue by rfcdejong** [Microsoft/Azure-SQL-DB-auditing-OMS-integration#24]
Until today it was working fine, and suddenly the Job fails

[07/20/2018 08:07:00 > 801899: SYS INFO] Status changed to Initializing
[07/20/2018 08:07:00 > 801899: SYS INFO] Run script 'SQLAuditLogsToOMSJob.exe' with script host - 'WindowsScriptHost'
[07/20/2018 08:07:00 > 801899: SYS INFO] Status changed to Running
[07/20/2018 08:07:02 > 801899: ERR ] 
[07/20/2018 08:07:02 > 801899: ERR ] Unhandled Exception: System.TypeInitializationException: The type initializer for 'XEL2OMS.Program' threw an exception. ---> Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'modified.TPRA.SqlDbAuditing_ServerAudit.Date', line 1, position 24576.
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.JsonTextReader.ParseProperty()
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[07/20/2018 08:07:02 > 801899: ERR ]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[07/20/2018 08:07:02 > 801899: ERR ]    at XEL2OMS.Program.GetStates(String fileName) in D:\home\site\repository\src\XEL2OMS\Program.cs:line 287
[07/20/2018 08:07:02 > 801899: ERR ]    at XEL2OMS.Program..cctor() in D:\home\site\repository\src\XEL2OMS\Program.cs:line 29
[07/20/2018 08:07:02 > 801899: ERR ]    --- End of inner exception stack trace ---
[07/20/2018 08:07:02 > 801899: ERR ]    at XEL2OMS.Program.Main() in D:\home\site\repository\src\XEL2OMS\Program.cs:line 340
[07/20/2018 08:07:02 > 801899: SYS INFO] Status changed to Failed
[07/20/2018 08:07:02 > 801899: SYS ERR ] Job failed due to exit code -532462766

**Comment by rfcdejong** [comment]
I deleted the source xel files and then deleted all xel files in AppData, restarted the webapp and somehow I keep getting the error. Any idea how to work around this?

**Comment by rfcdejong** [comment]
Deleted the states.json... seems to be running right now
